<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-08-31T02:56:56+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Fedresults',
    'version_installed' => '5.7.5.9',
    'misc' => array(
        'access_entity_updated' => 1470526627,
        'do_page_reindex_check' => false,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'white_label' => array(
        'background_image' => 'none',
    ),
    'theme' => array(
        'compress_preprocessor_output' => true,
        'generate_less_sourcemap' => false,
    ),
);
