<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-08-06T23:37:07+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.access_entity_updated
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Fedresults',
    'version_installed' => '5.7.5.9',
    'misc' => array(
        'access_entity_updated' => 1470526627,
    ),
);
